In [1]:
from Algorithms.KNN.ItemKNNCFRecommender import ItemKNNCFRecommender
from Utils.Toolkit import get_data

train = get_data()['train']
test = get_data()['test']

In [2]:
itemCF = ItemKNNCFRecommender(train.copy())

ItemKNNCFRecommender: URM Detected 6473 (20.94 %) cold users.
ItemKNNCFRecommender: URM Detected 3369 (18.22 %) cold items.


In [3]:
itemCF.fit(12, 88, similarity='tversky', normalize=True,
               feature_weighting='none', tversky_alpha=0.12331166243379268, tversky_beta=1.9752288743799558)

In [4]:
itemCF.recommend([0,1,2,3], 10)

[[6404, 10067, 5113, 10227, 6289, 5700, 7310, 17835, 13206, 5494],
 [7259, 6228, 5142, 8470, 6280, 18073, 3278, 8034, 4949, 17351],
 [4657, 4658, 11734, 735, 11733, 737, 739, 15908, 13837, 13206],
 [12328, 12327, 12334, 12333, 12332, 12331, 12330, 12329, 12336, 12324]]

In [5]:
user = 0

s = itemCF.W_sparse.indptr[user]
e = itemCF.W_sparse.indptr[user+1]

itemCF.W_sparse.data[s:e]

array([0.01111278, 0.01094776, 0.01106728, 0.01088896, 0.01112803],
      dtype=float32)

In [6]:
from Recommenders.CF.item_cf import ItemBasedCollaborativeFiltering

In [7]:
myItemCF = ItemBasedCollaborativeFiltering(12, 88, feature_weighting='none',
                                          similarity='tversky', tversky_alpha=0.12331166243379268,
                                          tversky_beta=1.9752288743799558, asymmetric_alpha=0.0)

In [8]:
myItemCF.fit(train)

In [13]:
myItemCF.recommend(1, 10)

array([ 7259,  6228,  5142,  8470,  6280, 18073,  3278,  8034,  4949,
       17351])

In [10]:
s1 = itemCF.W_sparse.indptr[user]
e1 = itemCF.W_sparse.indptr[user+1]

myItemCF.SM_item.data[s1:e1]

array([0.01111278, 0.01094776, 0.01106728, 0.01088896, 0.01112803],
      dtype=float32)

In [20]:
myItemCF.SM_item

<18495x18495 sparse matrix of type '<class 'numpy.float32'>'
	with 178959 stored elements in Compressed Sparse Row format>

In [21]:
myItemCF.RM

<30911x18495 sparse matrix of type '<class 'numpy.float64'>'
	with 3598314 stored elements in Compressed Sparse Row format>

In [26]:
myItemCF.RM.data[myItemCF.RM.indptr[0]:myItemCF.RM.indptr[1]]

array([0.03741507, 0.00200805, 0.00200855, 0.05052692, 0.00200855,
       0.00200855, 0.00278082, 0.00278082, 0.01116818, 0.00278082,
       0.00278082, 0.00278082, 0.00278082, 0.01659928, 0.01692846,
       0.01651477, 0.00857242, 0.01636481, 0.0079033 , 0.03414657,
       0.01535627, 0.00788793, 0.01528392, 0.02148644, 0.02146748,
       0.04859821, 0.00077169, 0.00077169, 0.00077169, 0.05187555,
       0.04723513, 0.04912255, 0.01941556, 0.00077169, 0.00152464,
       0.0391811 , 0.04384625, 0.02141674, 0.02314696, 0.00152464])

In [27]:
myItemCF.RM.indices[myItemCF.RM.indptr[0]:myItemCF.RM.indptr[1]]

array([17835, 13619, 10309, 10067,  9520,  1238, 17362, 17016, 15856,
       14679, 13227, 10996,  2603, 16171, 12713,  9168,  7647,  6416,
       16899, 13206, 11395,  8722,  8238,  7880,  7190, 10227,  9822,
        9425,  6627,  6404,  6289,  5113,  3601,   270, 11988,  7310,
        5700,  5696,  5494,   848], dtype=int32)

In [32]:
itemCF._compute_item_score(0)[itemCF._compute_item_score(0) > 0]

array([0.00077169, 0.00152464, 0.00200855, 0.00278082, 0.01941556,
       0.04912255, 0.02314696, 0.02141674, 0.04384625, 0.04723513,
       0.05187555, 0.01636481, 0.00077169, 0.02146748, 0.0391811 ,
       0.00857242, 0.02148644, 0.01528392, 0.00788793, 0.01651477,
       0.00077169, 0.00200855, 0.00077169, 0.05052692, 0.04859821,
       0.00200855, 0.00278082, 0.01535627, 0.00152464, 0.01692846,
       0.03414657, 0.00278082, 0.00200805, 0.00278082, 0.01116818,
       0.01659928, 0.0079033 , 0.00278082, 0.00278082, 0.03741507],
      dtype=float32)