In [1]:
from Algorithms.KNN.ItemKNNCFRecommender import ItemKNNCFRecommender
from Utils.Toolkit import get_data

train = get_data()['train']
test = get_data()['test']

In [2]:
itemCF = ItemKNNCFRecommender(train.copy())

ItemKNNCFRecommender: URM Detected 6473 (20.94 %) cold users.
ItemKNNCFRecommender: URM Detected 3394 (18.35 %) cold items.


In [3]:
itemCF.fit(29, 5, similarity='tanimoto')

In [4]:
itemCF.recommend(0, 10)

[3569, 6530, 7310, 724, 6404, 6289, 12713, 10469, 3572, 5518]

In [5]:
user = 0

s = itemCF.W_sparse.indptr[user]
e = itemCF.W_sparse.indptr[user+1]

itemCF.W_sparse.data[s:e]

array([0.07142857, 0.05882353, 0.02631579, 0.05      , 0.025     ,
       0.03448276, 0.07142857], dtype=float32)

In [6]:
from Recommenders.CF.item_cf import ItemBasedCollaborativeFiltering

In [7]:
myItemCF = ItemBasedCollaborativeFiltering(29, 5)

In [8]:
myItemCF.fit(train.copy())

In [9]:
myItemCF.recommend(0, 10)

array([ 3569,  6530,  7310,   724,  6404,  6289, 12713, 10469,  3572,
        5518])

In [10]:
s1 = itemCF.W_sparse.indptr[user]
e1 = itemCF.W_sparse.indptr[user+1]

myItemCF.SM_item.data[s1:e1]

array([0.07142857, 0.05882353, 0.02631579, 0.05      , 0.025     ,
       0.03448276, 0.07142857], dtype=float32)

In [11]:
WW_sparse = train.dot(itemCF.W_sparse)
WW_sparse

<30911x18495 sparse matrix of type '<class 'numpy.float64'>'
	with 12150835 stored elements in Compressed Sparse Row format>

In [12]:
import scipy.sparse as sps

m = sps.rand(10, 10, density=0.4, format='csr')
m.data[:] = 1
m.data

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])