In [30]:
import numpy as np
import scipy.sparse as sps

interactions = sps.rand(10, 10, density=0.5, format='csr')
interactions.data[:] = 1
interactions.todense()

matrix([[1., 1., 0., 0., 1., 1., 0., 0., 0., 0.],
        [1., 0., 1., 1., 0., 1., 0., 0., 1., 0.],
        [1., 1., 0., 1., 1., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 1., 1., 1., 1., 1., 0.],
        [0., 1., 0., 0., 1., 1., 1., 1., 1., 1.],
        [1., 0., 0., 1., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 1., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 1., 0., 0., 0., 0., 0., 1., 1., 0.],
        [1., 0., 1., 1., 1., 1., 0., 1., 1., 0.]])

In [33]:
items = sps.rand(10, 15, density=0.5, format='csr')
items.data[:] = 1
items.todense()

matrix([[0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1.],
        [0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 1.],
        [1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1.],
        [1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0.],
        [1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0.],
        [0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0.],
        [0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 0.],
        [1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1.]])

In [34]:
SM = np.zeros((interactions.shape[0], items.shape[1]), dtype=int)
SM

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [35]:
for user_id in range(interactions.shape[0]):
    u_start_pos = interactions.indptr[user_id]
    u_end_pos = interactions.indptr[user_id + 1]

    mask = interactions.indices[u_start_pos:u_end_pos]
    zero_mask = np.zeros(items.shape[1], dtype=int)

    if len(mask) > 0:
        features_matrix = items[mask,:].sum(axis=0)
        user_features = np.squeeze(np.asarray(features_matrix))
    else:
        user_features = zero_mask.copy()

    SM[user_id] = user_features

SM

array([[1, 2, 2, 3, 2, 2, 3, 2, 2, 3, 2, 1, 2, 2, 2],
       [4, 3, 0, 5, 3, 2, 2, 4, 3, 3, 2, 1, 2, 1, 2],
       [2, 3, 2, 4, 3, 2, 3, 3, 3, 4, 3, 1, 3, 2, 2],
       [3, 3, 2, 3, 2, 3, 4, 4, 2, 4, 4, 2, 2, 3, 1],
       [2, 3, 3, 4, 2, 3, 5, 4, 3, 5, 5, 2, 3, 5, 2],
       [2, 3, 2, 3, 3, 1, 3, 3, 3, 4, 3, 1, 2, 1, 1],
       [2, 3, 2, 3, 3, 3, 2, 3, 2, 3, 3, 2, 4, 3, 1],
       [0, 2, 1, 3, 1, 1, 2, 2, 2, 3, 1, 0, 1, 2, 3],
       [1, 3, 1, 3, 1, 1, 2, 2, 4, 3, 1, 0, 1, 2, 2],
       [4, 4, 1, 5, 3, 2, 4, 5, 4, 5, 4, 1, 2, 2, 2]])

In [40]:
items[[0,3,8],:].todense()

matrix([[0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1.],
        [1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0.],
        [1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [43]:
np.squeeze(np.asarray(items[[0,3,8],:].sum(axis=0)))

array([2., 2., 0., 3., 2., 0., 1., 2., 3., 2., 1., 0., 1., 0., 1.])

In [44]:
arr = np.array([9, 32, 12 , 13, 0, 0, 0, 0])
mask = np.flip(np.argsort(arr), 0)
arr[mask]

array([32, 13, 12,  9,  0,  0,  0,  0])

In [48]:
array = np.array([2, 3, 4, 5, 6])
array = np.where(array != 0, 1, array)
array

array([1, 1, 1, 1, 1])

In [50]:
array = np.array([5])
np.ediff1d(array)

array([], dtype=int64)